kumuluzee:
  name: rso-accounts
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/AccountsDS
      connection-url: jdbc:postgresql://172.17.0.1:5432/account
      username: dbuser
      password: postgres
      max-pool-size: 20
config:
  etcd:
    hosts: http://172.17.0.1:2379
  discovery:
    etcd:
      hosts: http://172.17.0.1:2379
app-properties:
  external-services:
    enabled: true