kumuluzee:
  name: smartarticle-accounts
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/AccountsDS
      connection-url: jdbc:postgresql://159.122.187.161:31613/account
      username: dbuser
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/AccountsDS
  config:
    etcd:
      hosts: http://159.122.187.161:32428
  discovery:
    etcd:
      hosts: http://159.122.187.161:32428
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="accounts">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="d07eec29-7fd5-4146-bedf-bbb76d36d9ba-ls.logit.io"
                                port="26367" protocol="tcp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info"/>
                                    <AppenderRef ref="logstash" level="trace"/>
                                </Root>
                            </Loggers>
                        </Configuration>'
  metrics:
    web-instrumentation:
    - name: accounts-endpoint
      url-pattern: /v1/accounts/*
app-properties:
  account-services:
    enabled: true
  account-institute-services:
    enabled: true
  account-article-services:
    enabled: true
  account-collection-services:
    enabled: true
  healthy: true