kumuluzee:
  name: smartarticle-accounts
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/AccountsDS
      connection-url: jdbc:postgresql://159.122.187.161:31613/account
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://159.122.187.161:32428
    discovery:
      etcd:
        hosts: http://159.122.187.161:32428
app-properties:
  account-services:
    enabled: true
  account-institute-services:
    enabled: true
  account-article-services:
    enabled: true
  account-collection-services:
    enabled: true